version: "3.9"
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        mc config host add local http://minio:9000 minioadmin minioadmin --api s3v4;
        mc mb -p local/my-mysql-backups || true;
        mc anonymous set download local/my-mysql-backups || true;
        sleep 3;
        echo 'MinIO bucket ensured';
      "

  src-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: srcpassword
      MYSQL_DATABASE: mydb
    ports:
      - "33060:3306"
    volumes:
      - src-mysql-data:/var/lib/mysql

  tgt-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tgtpassword
      MYSQL_DATABASE: mydb
    ports:
      - "33061:3306"
    volumes:
      - tgt-mysql-data:/var/lib/mysql

  snapmysql:
    build: .
    image: snapmysql:dev
    env_file: .env
    depends_on:
      - src-mysql
      - tgt-mysql
      - minio
      - minio-setup
    restart: unless-stopped

volumes:
  minio-data:
  src-mysql-data:
  tgt-mysql-data:
