apiVersion: v1
kind: Secret
metadata:
  name: snapmysql-secrets
  namespace: app
type: Opaque
stringData:
  # Source DB
  SRC_DB_HOST: your-source-host.rds.amazonaws.com
  SRC_DB_PORT: "3306"
  SRC_DB_USER: backup_user
  SRC_DB_PASSWORD: supersecret
  SRC_DB_NAME: mydb

  # Target DB
  TGT_DB_HOST: your-target-host.do.db
  TGT_DB_PORT: "25060"
  TGT_DB_USER: admin
  TGT_DB_PASSWORD: supersecret
  TGT_DB_NAME: mydb

  # S3/Spaces
  S3_ENDPOINT: https://nyc3.digitaloceanspaces.com
  S3_REGION: us-east-1
  S3_BUCKET: my-mysql-backups
  S3_ACCESS_KEY_ID: DO_SPACES_KEY
  S3_SECRET_ACCESS_KEY: DO_SPACES_SECRET

  # Slack
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/T000/B000/XXXX
